package com.clauderemote.integration

import com.clauderemote.connection.SshManager
import com.clauderemote.model.ClaudeMode
import com.clauderemote.model.ClaudeModel
import com.clauderemote.session.service.SessionPersistenceService
import com.clauderemote.storage.PersistedSession
import com.clauderemote.storage.ServerStorage
import com.clauderemote.storage.SessionStorage
import com.jcraft.jsch.Session
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Before
import org.junit.Test
import java.io.File
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * The embedded restore.sh / drift.sh, end to end: installed by the real
 * [SessionPersistenceService.INSTALL_RESTORE_COMMAND] over a real SSH connection,
 * fed a manifest produced by the real [SessionStorage.serializeForServer], and run
 * against a real tmux server.
 *
 * The highest-value test here is [restoreRecreatesTheSessionsTheAppSerialized]: it
 * is the only thing anywhere that checks the Kotlin producer against the jq
 * consumer. `restore.sh` reads `.[i].tmuxSessionName`, `.folder`, `.mode`,
 * `.model`, `.claudeSessionId` off a TOP-LEVEL ARRAY; nothing else verifies that
 * `serializeForServer` still emits exactly that, so renaming a
 * [PersistedSession] field would silently break restore for every user.
 *
 * Each test gets its OWN fixture. restore.sh's source precedence
 * (sessions.restore.json > its .bak > sessions.json > ... ) means a manifest left
 * by one test would change which file the next one actually reads, so a shared
 * fixture would couple them invisibly.
 */
class RestoreScriptIntegrationTest {

    private lateinit var fixture: SshdFixture
    private lateinit var manager: SshManager
    private lateinit var session: Session

    @Before
    fun boot() {
        // NO SILENT SKIP. The Gradle task already refuses to run without
        // sshd/tmux/jq (see :shared:integrationTest's doFirst), so an unsupported
        // box HERE is a wiring problem — and a JUnit "skipped" on these tests is
        // indistinguishable from a pass in CI. Fail loudly, naming what is missing.
        SshdFixture.unsupportedReason?.let {
            error("integration environment incomplete — $it")
        }
        fixture = SshdFixture.start()
        manager = SshManager(ServerStorage(InMemoryKeyValueStore()))
        runBlocking { manager.connect(fixture.server, onOutput = {}, onConnectionLost = {}) }
        session = assertNotNull(manager.getSession())
    }

    @After
    fun shutdown() {
        // Order matters: see shutdownForTest for why the raw session dies first.
        if (::manager.isInitialized) manager.shutdownForTest()
        if (::fixture.isInitialized) fixture.close()
    }

    @Test
    fun installWritesBothScriptsCarryingTheCurrentMarker() {
        val out = install()
        assertContains(out, "RESTORE_SCRIPT_INSTALLED", message = "install must report writing restore.sh")
        assertContains(out, "DRIFT_SCRIPT_INSTALLED", message = "install must report writing drift.sh")

        val restore = File(fixture.home, ".claude-remote/restore.sh")
        val drift = File(fixture.home, ".claude-remote/drift.sh")
        assertTrue(restore.isFile, "restore.sh must exist at ${restore.absolutePath}")
        assertTrue(drift.isFile, "drift.sh must exist at ${drift.absolutePath}")
        assertTrue(restore.canExecute(), "restore.sh must be chmod +x")
        assertTrue(drift.canExecute(), "drift.sh must be chmod +x")
        assertContains(restore.readText(), currentMarker, message = "restore.sh must carry $currentMarker")
        assertContains(drift.readText(), currentMarker, message = "drift.sh must carry $currentMarker")

        // Re-running must take the no-op PRESENT path, not rewrite (a rewrite on
        // every connect is what used to revert in-place fixes).
        val second = install()
        assertContains(second, "RESTORE_SCRIPT_PRESENT", message = "second install must detect the marker")
        assertFalse(
            second.contains("RESTORE_SCRIPT_INSTALLED"),
            "second install must NOT rewrite restore.sh:\n$second",
        )
    }

    /**
     * PRODUCER/CONSUMER CONTRACT + idempotency. The manifest is generated by the
     * app's own serializer and uploaded through the app's own uploadFile — no
     * hand-written JSON anywhere, which is the whole point.
     */
    @Test
    fun restoreRecreatesTheSessionsTheAppSerialized() {
        install()

        val alpha = "claude-server-int--alpha"
        val beta = "claude-server-int--beta"
        val folderA = File(fixture.home, "projA").apply { mkdirs() }
        val folderB = File(fixture.home, "projB").apply { mkdirs() }

        val manifest = serializeWithApp(
            persisted(id = "s1", tmux = alpha, folder = folderA, mode = ClaudeMode.YOLO, model = ClaudeModel.DEFAULT),
            persisted(id = "s2", tmux = beta, folder = folderB, mode = ClaudeMode.NORMAL, model = ClaudeModel.SONNET),
        )
        // Sanity-check the produced shape is what jq is about to be handed.
        assertTrue(manifest.trimStart().startsWith("["), "serializeForServer must emit a top-level ARRAY, got:\n$manifest")
        uploadManifest("sessions.json", manifest)

        // MUST pre-start the server: with none reachable, restore.sh tries
        // `systemd-run --user --scope tmux new-session` and, on failure, logs
        // "skipping restore" and exits 0 having done NOTHING — a vacuous pass.
        fixture.startTmuxServer()

        val run = runRestore()
        assertEquals(0, run.exit, "restore.sh should exit 0. log:\n${fixture.restoreLog()}")

        waitUntil(20_000, "restore.sh to recreate $alpha and $beta. log:\n${fixture.restoreLog()}") {
            fixture.tmuxSessions().containsAll(listOf(alpha, beta))
        }

        val log = fixture.restoreLog()
        assertRestoreLogIsClean(log)
        assertContains(log, "Restored $alpha", message = "restore.log should record $alpha. log:\n$log")
        assertContains(log, "Restored $beta", message = "restore.log should record $beta. log:\n$log")
        assertContains(
            log,
            File(fixture.home, ".claude-remote/sessions.json").absolutePath,
            message = "restore.sh should have read the manifest we uploaded. log:\n$log",
        )

        // IDEMPOTENT: a second run must not duplicate anything. (drift.sh's
        // self-heal re-runs restore.sh on every tick, so this is load-bearing.)
        val before = fixture.tmuxSessions().sorted()
        val second = runRestore()
        assertEquals(0, second.exit, "second restore.sh should exit 0. log:\n${fixture.restoreLog()}")
        Thread.sleep(500) // let any (unwanted) creation land before we look
        assertEquals(
            before,
            fixture.tmuxSessions().sorted(),
            "a second restore.sh must not create or duplicate sessions. log:\n${fixture.restoreLog()}",
        )
        assertRestoreLogIsClean(fixture.restoreLog())
    }

    /**
     * The teeth of the contract test above, made permanent. If a
     * [PersistedSession] field is ever renamed, the manifest jq reads loses
     * `tmuxSessionName` — and this is what that looks like: the expected sessions
     * are simply never created. A green [restoreRecreatesTheSessionsTheAppSerialized]
     * therefore genuinely means the field names still line up.
     */
    @Test
    fun restoreCreatesNothingWhenTheManifestFieldIsRenamed() {
        install()
        val expected = "claude-server-int--renamed"
        val folder = File(fixture.home, "projRenamed").apply { mkdirs() }

        val broken = serializeWithApp(
            persisted(id = "s1", tmux = expected, folder = folder),
        ).replace("\"tmuxSessionName\"", "\"tmuxName\"")
        assertFalse(broken.contains("tmuxSessionName"), "precondition: the field must be renamed away")
        uploadManifest("sessions.json", broken)

        fixture.startTmuxServer()
        runRestore()

        // Give restore.sh the same chance to succeed the positive test gets.
        Thread.sleep(2_000)
        assertFalse(
            fixture.tmuxSessions().contains(expected),
            "with tmuxSessionName renamed, restore.sh must NOT have created $expected — " +
                "if it did, the contract assertion has no teeth. log:\n${fixture.restoreLog()}",
        )
    }

    /**
     * drift.sh self-heal. Sequence matters and mirrors production: drift builds
     * its server-owned manifest (sessions.restore.json) from the LIVE tmux
     * sessions on tick N, so only from tick N+1 can it notice one has died. The
     * timer runs every 60s, so in the field the two ticks are just consecutive
     * minutes.
     *
     * drift.sh's single `systemctl` reference is the shutdown guard
     * (`systemctl is-system-running` -> skip reconcile while stopping/offline).
     * It is on the path that matters, so the fixture shims systemctl to answer
     * "running"; with no systemctl at all the guard's `|| true` leaves STATE
     * empty and also falls through, so this makes the behaviour deterministic
     * rather than changing it.
     */
    @Test
    fun driftRelaunchesOnlyTheKilledSession() {
        install()

        val alpha = "claude-server-int--alpha"
        val beta = "claude-server-int--beta"
        val folderA = File(fixture.home, "projA").apply { mkdirs() }
        val folderB = File(fixture.home, "projB").apply { mkdirs() }
        uploadManifest(
            "sessions.json",
            serializeWithApp(
                persisted(id = "s1", tmux = alpha, folder = folderA),
                persisted(id = "s2", tmux = beta, folder = folderB),
            ),
        )
        fixture.startTmuxServer()
        runRestore()
        waitUntil(20_000, "both sessions restored. log:\n${fixture.restoreLog()}") {
            fixture.tmuxSessions().containsAll(listOf(alpha, beta))
        }

        // Tick 1: seed the server-owned manifest from live tmux.
        assertEquals(0, runDrift().exit, "drift tick 1 should exit 0. log:\n${fixture.driftLog()}")
        val restoreSrc = File(fixture.home, ".claude-remote/sessions.restore.json")
        waitUntil(10_000, "drift to write ${restoreSrc.name}. log:\n${fixture.driftLog()}") {
            restoreSrc.isFile && restoreSrc.readText().contains(alpha) &&
                restoreSrc.readText().contains(beta)
        }

        val betaBorn = assertNotNull(fixture.sessionCreatedAt(beta), "beta must be alive before the kill")

        // Kill exactly one, on the PRIVATE socket (see SshdFixture's safety note).
        assertEquals(
            0,
            fixture.tmux("kill-session", "-t", "=$alpha").exit,
            "could not kill $alpha on the private socket",
        )
        waitUntil(10_000, "$alpha to be gone") { !fixture.tmuxSessions().contains(alpha) }

        // Tick 2: self-heal.
        assertEquals(0, runDrift().exit, "drift tick 2 should exit 0. log:\n${fixture.driftLog()}")
        waitUntil(25_000, "drift.sh to self-heal $alpha. log:\n${fixture.driftLog()}") {
            fixture.tmuxSessions().contains(alpha)
        }
        assertContains(
            fixture.driftLog(),
            "self-heal",
            message = "drift.log should record the self-heal decision:\n${fixture.driftLog()}",
        )

        // The healthy one must be untouched — same session, not killed+recreated.
        assertTrue(fixture.tmuxSessions().contains(beta), "$beta must still exist")
        assertEquals(
            betaBorn,
            fixture.sessionCreatedAt(beta),
            "$beta was recreated (session_created changed) — self-heal must only touch what died",
        )
        assertRestoreLogIsClean(fixture.restoreLog())
    }

    // ------------------------------------------------------------------ helpers

    /**
     * Install using the REAL production command, piped over stdin so its embedded
     * heredocs and quoting are transmitted verbatim.
     *
     * Note we run the constant ourselves rather than calling
     * `installRestoreService(...)`: that method opens its own exec channel with no
     * env prefix, and under this fixture the sandbox is enforced server-side by
     * sshd's ForceCommand, so the constant IS the production payload either way.
     */
    private fun install(): String {
        val result = session.execCapture(
            "bash -s",
            timeoutMs = 60_000,
            stdin = SessionPersistenceService.INSTALL_RESTORE_COMMAND.toByteArray(),
        )
        assertEquals(0, result.exit, "install command failed:\n${result.out}")
        return result.out
    }

    private fun runRestore(): ExecResult =
        session.execCapture("bash \"\$HOME/.claude-remote/restore.sh\"", timeoutMs = 60_000)

    private fun runDrift(): ExecResult =
        session.execCapture("bash \"\$HOME/.claude-remote/drift.sh\"", timeoutMs = 60_000)

    /** Produce the manifest with the APP's serializer — never hand-written JSON. */
    private fun serializeWithApp(vararg sessions: PersistedSession): String {
        val storage = SessionStorage(InMemoryKeyValueStore())
        sessions.forEach { storage.upsert(it) }
        // A session on ANOTHER server must not leak into this server's manifest.
        storage.upsert(
            sessions.first().copy(id = "other", serverId = "other-server", tmuxSessionName = "claude-server-other--x"),
        )
        val json = storage.serializeForServer(SERVER_ID)
        assertFalse(json.contains("claude-server-other--x"), "serializeForServer must filter by serverId")
        return json
    }

    private fun persisted(
        id: String,
        tmux: String,
        folder: File,
        mode: ClaudeMode = ClaudeMode.YOLO,
        model: ClaudeModel = ClaudeModel.DEFAULT,
    ) = PersistedSession(
        id = id,
        serverId = SERVER_ID,
        folder = folder.absolutePath,
        mode = mode,
        model = model,
        tmuxSessionName = tmux,
        alias = tmux.substringAfterLast("--"),
        claudeSessionId = null,
        createdAt = 0L,
    )

    /** Upload through the app's real uploadFile path (exec channel + cat). */
    private fun uploadManifest(name: String, json: String) {
        val dir = File(fixture.home, ".claude-remote")
        runBlocking { manager.uploadFile(json.toByteArray(), dir.absolutePath, name) }
        val landed = File(dir, name)
        waitUntil(10_000, "manifest $name to land at ${landed.absolutePath}") { landed.isFile }
        assertEquals(json, landed.readText(), "uploaded manifest must match byte for byte")
    }

    /**
     * restore.sh writes NOTHING to stdout (`exec >> restore.log`), so its log is
     * the only diagnostic — and these four lines are its silent-failure modes.
     */
    private fun assertRestoreLogIsClean(log: String) {
        for (bad in listOf(
            "skipping restore",       // no tmux server: exits 0 doing nothing
            "FAILED to restore",      // tmux new-session rejected the request
            "invalid session",        // manifest entry tmux would not accept
            "Cannot index object",    // jq handed an object where it wants an array
            "not in PATH",            // tmux/claude missing
            "nothing to restore",     // manifest never found
        )) {
            assertFalse(log.contains(bad), "restore.log contains \"$bad\":\n$log")
        }
    }

    companion object {
        private const val SERVER_ID = "integration-server"

        /** The marker the CURRENT build installs, read from the production constant. */
        private val currentMarker: String by lazy {
            val m = Regex("""MARKER="(claude-remote-restore-v\d+)"""")
                .find(SessionPersistenceService.INSTALL_RESTORE_COMMAND)
            assertNotNull(m, "could not find MARKER=... in INSTALL_RESTORE_COMMAND")
            m.groupValues[1]
        }
    }
}
